FROM ubuntu

RUN apt update -y && apt install -y libsodium-dev libsecp256k1-dev libgmp-dev

RUN wget https://ligolang.org/bin/linux/ligo

RUN chmod +x ./ligo

RUN cp ./ligo /usr/local/bin

COPY . .

RUN ligo compile contract contract/main/main.mligo -e main --michelson-format json > deploy/ressources/Farm.json

WORKDIR /deploy

RUN npm i

RUN tsc

RUN node deployFarmDb.js > .env

ENTRYPOINT [ "node deploy.js" ]