name: Run Python Tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build -f Dockerfile.test . -t farms:latest
      - name: Run tests
        run: |
          docker run farms:latest
      - name: Deployment
        working-directory: ./deploy
        run: |
          docker-compose build
          docker-compose up


