name: Run Python Tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build . -t farms:latest
      - name: Run tests
        run: |
          docker run farms:latest
      - name: Deployment
        working-directory: ./deploy
        run: |
          docker pull tqtezos/flextesa:20211025
          docker run --rm --name hangz --detach -p 20000:20000 tqtezos/flextesa:20211025 hangzbox start
          npm i
          bash deploy.sh
